FROM registry.access.redhat.com/ubi9/python-311

USER 0

RUN yum upgrade -y && yum install -y \
    make \
    findutils \
    wget numactl-libs \
    libgcc gcc gcc-c++ \
    && yum clean all \
    && rm -rf /var/cache/yum/*


##############
# vLLM Layer #
##############

WORKDIR /opt/app-root/src

USER 1001

RUN pip install --upgrade pip \
    && pip install wheel packaging ninja setuptools>=49.4.0 numpy

COPY --chown=1001:0 ./ /opt/app-root/src

RUN pip install -v --no-cache-dir -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

# Fix permissions to support pip in Openshift environments \
RUN chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P


RUN VLLM_TARGET_DEVICE=cpu python3 setup.py install

EXPOSE 8000 8080

WORKDIR /opt/app-root/lib64/python3.11/site-packages/vllm-0.4.2+cpu-py3.11-linux-x86_64.egg

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]

