apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: vLLM CPU
  name: vllm-ccpu
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - --model
        - /mnt/models/
        - --dtype
        - float16
        - --max-model-len
        - "5900"
        - --download-dir
        - /models-cache
        - --port
        - "8080"
      image: quay.io/avitui/vllm-cpu:v1.4
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
  nodeSelector:
    vllm-node: cpu
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
